services:
  - type: web
    name: daratopup-frontend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        value: https://nadybackend.onrender.com
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://nadybackend.onrender.com
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        value: "570013043660-p5uujjtc2sq24si85q3thmliqnf3s9uc.apps.googleusercontent.com"
