services:
  - type: web
    name: daratopup-frontend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        value: https://daratopup-backend-1.onrender.com
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://daratopup-backend-1.onrender.com
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        value: "206329302084-7h656a65vmoeusu10c0cor9lvbp3042v.apps.googleusercontent.com"
